### PR TITLE
Added "About Us" page landing section

### PR DESCRIPTION
**Pull request by MohitSharma-21**
Resolved: #20  

image

### CODE REVIEW

**Review by DivyanshuParwal — CHANGES_REQUESTED** [review]
@MohitSharma-21  The Image and text is not visible in the deploy preview.

**Comment by MohitSharma-21** [comment]
@DivyanshuParwal  now it is visible

**Comment by paulcretu** [comment]
Since this one is really similar to #56 and #60, let's wait on those before proceeding

**Comment by paulcretu** [comment]
Now that we have the `TopBanner` component added in #56, let's use that instead of copying the code. Closing this, feel free to re-open or make a new PR (or really we should just do a single PR to finish replacing all the top sections)

**Pull request closed without merging**
