### PR TITLE
Add `TopBanner` component to all pages

### PR DESCRIPTION
**Pull request by MohitSharma-21**
Added TopBanner for all pages

### CODE REVIEW

**Review by paulcretu — CHANGES_REQUESTED** [review]
@MohitSharma-21 thanks for taking the initiative to change this for all the pages. Can you merge in the latest changes and update to use the latest version of `TopBanner`? Once that's done I can merge

**Comment by MohitSharma-21** [comment]
@ShwetKhatri2001 @paulcretu Sorry for the late reply, actually I was sick for some days. I would surely make the requested changes.

**Comment by paulcretu** [comment]
No worries, whenever you have time, it's no rush. Hope you're feeling better

**Comment by MohitSharma-21** [comment]
> No worries, whenever you have time, it's no rush. Hope you're feeling better
Yes, now I'm totally fine and I have made the changes. Please let me know if there is something wrong or need to be updated.

**Review by paulcretu — APPROVED** [review]

**Pull request merged**
