### PR TITLE
Network org logos

### PR DESCRIPTION
**Pull request by UXBrendan**
I'm trying to upload image files of our network partner logos for the Donate page.

### CODE REVIEW

**Review by scottveirs — APPROVED** [review]
Just added files, but may want to organize in a sub-directory later.

**Review by NayoBaez — APPROVED** [review]
Approved upload images

**Comment by scottveirs** [comment]
@UXBrendan I noticed a few of these logos already exist in the `images` directory, albeit at different resolutions. For example, there are a handful of them already [https://github.com/orcasound/orcahome/tree/main/public/images/getinvolved](here -- 
https://github.com/orcasound/orcahome/tree/main/public/images/getinvolved) ...but with file names that have abbreviations of the organizations' names, whereas it looks like in most cases you wrote out the org names. (BTW, this one should probably be renamed to not have spaces in the file name.)

**Do you think they should all be the same place, e.g. a sub-directory with a sensible name, like `organization-logos` ?**

And do you like the abbreviations, or should we write them out so they are human-readable?

Depending on your answers, I could reorganize a bit before we merge them in, or @NayoBaez could do so. We just have to be careful to also adjust the code currently using the extant files if we change their names!

**Comment by UXBrendan** [comment]
Logo locations:
**Repo:** orcahome
**Folder:** "public" > "getinvolved"
- Center for Whale Research
- Oceans Initiative (Does not match)
- Cetacean Research Technology
- Deep Green Wilderness
- F.O.L.K.S.
- Pacmam (Does not match, not sure if we actually have it)
- The Whale Trail
- Whale Scout (Does not match)

**Folder:** "public" > "learn"
- Orca Behavior Institute
- Orca Network
- Port Townsend Marine Science Center

**Comment by UXBrendan** [comment]
Since needed logos are located in existing folders, this PR is not needed.

**Pull request closed without merging**
