### PR TITLE
Updated css to fix styling issues

### PR DESCRIPTION
**Pull request by imacchiavello**
Change margin sizes to fix overflowing issues and make them fully responsive

### CODE REVIEW

**Comment by paulcretu** [comment]
@imacchiavello looks like this PR isn't building, see the netlify logs for errors https://app.netlify.com/sites/orcahome/deploys/6117f3f6c536440007cc3ee9

**Comment by scottveirs** [comment]
Hey @imacchiavello -- I'm new to Netlify build logs, but here's one potential bug:

In this line

import orcas from '../images/srkw2-10.jpg''

I think there may be an extra trailing single quote, i.e. two ' symbols.

**Comment by paulcretu** [comment]
@imacchiavello I would like to review this PR (sorry it's taken so long!) but it could really use some formatting/linting. Can you install the [eslint](https://marketplace.visualstudio.com/items?itemName=dbaeumer.vscode-eslint) and [prettier](https://marketplace.visualstudio.com/items?itemName=esbenp.prettier-vscode) VS Code extensions (good to have these anyway), reformat the code, and push the commit onto this branch? Once you install those extensions, it should auto-format when you save each file, or you can use `npm run format` and `npm run lint:fix` to reformat all the files in one pass. If you need help let me know. Otherwise I can also do it but I want to give you the opportunity to learn and get your dev environment set up properly!

In general it just makes things a lot easier to review—and it saves some back and forth of giving you feedback about formatting issues.

**Review by prafulfillment — APPROVED** [review]

**Comment by prafulfillment** [comment]
Can be closed as this is being resolved in #14

**Comment by paulcretu** [comment]
Ended up merging #14 since it's using MUI and effectively is a refactor of this PR. Closing this one.

**Pull request closed without merging**
